# events {
#     worker_connections 1024;
# }

# {
#     http 
# stream {
#     # Nginx listens on a public port and forwards to the private network
#     server {
#         listen 8080;
#         proxy_pass postgres_db:5432;
#     }
# }
# ##############################################################
# events { 
#   worker_connections 1024;
#  }

# http {
#     server {
#         listen 8080;

#         location /api/logs {
#             # Only allow GET (read) requests from the public internet
#             limit_except GET {
#                 deny all;
#             }
            
#             # Forward safe requests to an internal app container
#             proxy_pass http://app_backend:3000;
#         }
#     }
# }

######################################################################
events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://app_backend:3000; # Routes to the backend container internally
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}